---
authors:
  - name: Emi Tanaka
    thanks: Corresponding author
    department: Department of Econometrics and Business Statistics
    affiliation: Monash University
    location: Clayton, VIC 3800
    email: emi.tanaka@monash.edu
  - name: Dewi Amaliah
    department: Department of Econometrics and Business Statistics
    affiliation: Monash University
    location: Clayton, VIC 3800
header-includes: |
  \usepackage{colortbl}
  \usepackage{bera}
  \usepackage{xcolor}
  \usepackage{hyperref}
  \usepackage[utf8]{inputenc}
  \def\tightlist{}
  \newcommand{\ctv}[1]{\href{http://CRAN.R-project.org/view=#1}{\emph{#1}}}
bibliography: paper.bib
biblio-style: unsrt
#preamble: >
output: 
  rticles::arxiv_article:
    keep_tex: true
---

```{r, include = FALSE}
file.copy(here::here("paper.bib"), here::here("paper/arxiv/paper.bib"))
file.copy(here::here("supp.pdf"), here::here("paper/arxiv/anc/supp.pdf"))
zip("anc", "anc/")

paper <- here::here("paper.Rmd")
meta <- rmarkdown::yaml_front_matter(paper)
```

---
title: "`r meta$title`"
abstract: >
  `r meta$abstract`
---

```{r child=paper}
```

