---
title: "doe-pkgs-analysis"
author: "Dewi Lestari Amaliah - 31251587"
date: "15/08/2021"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(yaml)
library(reshape)
library(tidyverse)
library(lubridate)
library(splitstackshape)
library(igraph)
library(geomnet)
library(ggnetwork)
library(tidygraph)
library(ggraph)
library(networkD3)
library(plotly)
library(qdapRegex)
library(shiny)
library(visNetwork)
library(forcats)
```

```{r}
#load the yml file and transform it as data frame
pkg_df <- yaml.load_file(here::here("data/input/doe-pkgs.yml")) %>%
  melt()

#tidy the data frame
pkg_tidy <- pkg_df %>%
  pivot_wider(names_from = L3,
              values_from = value)
  

# pivot longer the data frame by its type 
pkg_tidy_long_type <- pkg_tidy %>%
  unnest(type) %>%
  unnest(date) %>%
  unnest(domain) %>%
  mutate(year = year(ymd(date))) 

```

```{r}
# summarise the packages based on its type
pkg_type <- pkg_tidy_long_type %>%
  group_by(L2) %>%
  slice_head(n = 1) %>%
  mutate(year = factor(year, level = c("2009", "2011", "2012", "2013",
                                       "2014", "2015", "2016", "2017",
                                       "2018", "2019", "2020", "2021")))
```

```{r}
#summarise the package based on its date of published 
pkg_year <- pkg_type %>%
  group_by(year) %>%
  count() %>%
  ungroup()


ggplot(pkg_year, aes(x = year, y = n, group = 1)) +
  geom_line() +
  geom_point()
```

## Create Sankey Diagram for packages' type

```{r}
sankey_data <- pkg_type %>%
  select(domain, type) %>%
  group_by(domain, type) %>%
  count() %>%
  ungroup()

domain <- sankey_data %>%
  distinct(domain) %>%
  rename(node = domain)

type <- sankey_data %>%
  distinct(node = type)

db_sankey <- rbind(domain, type)

routes_sankey <- graph_from_data_frame(d = sankey_data, vertices = db_sankey, directed = TRUE)

routes_sankey_tidy <- routes_sankey %>% as_tbl_graph() %>%
  activate(edges)

nodes_sankey <- db_sankey %>%
  rowid_to_column("id") %>%
  mutate(id = id - 1)

edges_sankey <-routes_sankey_tidy %>%
  activate(edges) %>%
  data.frame() %>%
  mutate(from = from - 1,
         to = to - 1)

sankeyNetwork(Links = edges_sankey, Nodes = nodes_sankey, Source = 'from', 
                         Target = 'to', Value = 'n', NodeID = 'node',
                         units = 'packages')
```

# The domain of package based on year 

```{r}
pkg_type_year <- pkg_type %>%
  group_by(year, domain) %>%
  count() %>%
  ungroup() %>%
  left_join(pkg_year, by="year", suffix = c("_dom", "_year")) %>%
  mutate(pct = round(n_dom/n_year*100, 0)) %>%
  mutate(dom = case_when(domain == "general" ~ "Gral",
                         domain == "clinical trial" ~ "CT",
                         domain == "genetics" ~ "Gtic",
                         domain == "computer experiment" ~ "CE",
                         domain == "agriculture" ~ "Ag",
                         domain == "industrial experiment" ~ "IE",
                         domain == "environmental science" ~ "Env.S",
                         domain == "consumer behaviour" ~ "CB",
                         domain == "equivalence studies" ~ "Eq.S",
                         domain == "geospatial study" ~ "GS",
                         domain == "microbiology" ~ "Mbg",
                         domain == "sensory studies" ~ "SS"))

ggplot(pkg_type_year, aes(x = pct, y = dom)) +
  geom_col() +
  facet_wrap(~year, scales = "free_y") +
  theme_bw()


pkg_type_year %>%
  mutate(dom = reorder(dom, pct)) %>%
  group_by(year, dom) %>%
  arrange(desc(pct)) %>%
  ungroup() %>%
  mutate(dom = factor(paste(dom, year, sep = "__"), 
                       levels = rev(paste(dom, year, sep = "__")))) %>%
  ggplot(aes(dom, pct)) +
  geom_col() +
  geom_text(aes(label=pct), size = 3, color = "black", 
            hjust = -0.05, vjust=-0.05) +
  facet_wrap(~year, scales = "free_y") +
  scale_x_discrete(labels = function(x) gsub("__.+$", "", x)) +
  coord_flip() +
  theme_bw() +
  xlab("Domain") +
  ylab("Percentage") +
  theme(panel.grid.major.y = element_blank()) 
 
```



